services:
  app:
    build:
      context: .
      target: test
    container_name: code-finances-api-test
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/var/www
    env_file:
      - .env.test
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: 'no'
    networks:
      - code-finances-net-test
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096m
  db:
    container_name: code-finances-db-test
    image: postgres:14.3
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    networks:
      - code-finances-net-test
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${DB_USER}',
          '-d',
          '${DB_NAME}',
          '-h',
          'localhost',
          '-p',
          '5432',
        ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  rabbitmq:
    container_name: 'rabbitmq-code-finances-test'
    image: rabbitmq:3-management
    ports:
      - '5002:5672'
      - '15002:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - code-finances-net-test

networks:
  code-finances-net-test:
    driver: bridge
